[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/python-trovo?ref=main"

[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/multifirefox?ref=main"

[[sources]]
type = "git"
url = "git+https://github.com/hannesgith/rquickshare?ref=flake"

[[sources]]
type = "git"
url = "git+https://github.com/hannesgith/neohtop?ref=nixify"

[[sources]]
type = "git"
url = "git+https://github.com/raboof/octopin?ref=nix"

[[sources]]
type = "git"
url = "git+https://github.com/TamtamHero/fw-fanctrl?ref=packaging/nix"

[[sources]]
type = "github"
owner = "anpandey"
repo = "numen-nix"

[[sources]]
# Please open upstream issue when removing:
# https://github.com/astro/microvm.nix/issues/new
type = "github"
owner = "astro"
repo = "microvm.nix"

[[sources]]
type = "github"
owner = "atuinsh"
repo = "atuin"

[[sources]]
type = "github"
owner = "bobvanderlinden"
repo = "nixpkgs-ruby"

[[sources]]
type = "github"
owner = "brizzbuzz"
repo = "opnix"

[[sources]]
type = "github"
owner = "CertainLach"
repo = "fleet"

[[sources]]
type = "github"
owner = "chaotic-cx"
repo = "nyx"

[[sources]]
type = "github"
owner = "dgollings"
repo = "nix-atlas"

[[sources]]
type = "github"
owner = "edolstra"
repo = "flake-compat"

[[sources]]
type = "github"
owner = "eza-community"
repo = "eza"

[[sources]]
type = "github"
owner = "fort-nix"
repo = "nix-bitcoin"

[[sources]]
type = "github"
owner = "helix-editor"
repo = "helix"

[[sources]]
type = "github"
owner = "hellwolf"
repo = "solc.nix"

[[sources]]
type = "github"
owner = "hercules-ci"
repo = "flake-parts"

[[sources]]
type = "github"
owner = "hyprwm"
repo = "hyprland"

[[sources]]
type = "github"
owner = "input-output-hk"
repo = "haskell.nix"

[[sources]]
type = "github"
owner = "jj-vcs"
repo = "jj"

[[sources]]
type = "github"
owner = "jonahbron"
repo = "micropython-builder"

[[sources]]
type = "github"
owner = "juliosueiras-nix"
repo = "nix-security"

[[sources]]
type = "github"
owner = "kashw2"
repo = "bitbucket-runner-nix"

[[sources]]
type = "github"
owner = "lnbits"
repo = "lnbits-legend"

[[sources]]
type = "github"
owner = "matthewcroughan"
repo = "filestash-nix"

[[sources]]
type = "github"
owner = "Mic92"
repo = "sops-nix"

[[sources]]
type = "github"
owner = "mirrexagon"
repo = "nixpkgs-esp-dev"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "lightmeter"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "offen"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "openpgp-ca"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "weblate"

[[sources]]
type = "github"
owner = "nix-community"
repo = "authentik-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "autofirma-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "browser-previews"

[[sources]]
type = "github"
owner = "nix-community"
repo = "buildbot-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "comma"

[[sources]]
type = "github"
owner = "nix-community"
repo = "crate2nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "crystal2nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "disko"

[[sources]]
type = "github"
owner = "nix-community"
repo = "disko-templates"

[[sources]]
type = "github"
owner = "nix-community"
repo = "dns.nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "dream2nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "emacs-overlay"

[[sources]]
type = "github"
owner = "nix-community"
repo = "ethereum.nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "fenix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "flake-compat"

[[sources]]
type = "github"
owner = "nix-community"
repo = "flake-firefox-nightly"

[[sources]]
type = "github"
owner = "nix-community"
repo = "flake-nimble"

[[sources]]
type = "github"
owner = "nix-community"
repo = "flakelight"

[[sources]]
type = "github"
owner = "nix-community"
repo = "go-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "gomod2nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "harmonia"

[[sources]]
type = "github"
owner = "nix-community"
repo = "haumea"

[[sources]]
type = "github"
owner = "nix-community"
repo = "home-manager"

[[sources]]
type = "github"
owner = "nix-community"
repo = "hydra-check"

[[sources]]
type = "github"
owner = "nix-community"
repo = "impermanence"

[[sources]]
type = "github"
owner = "nix-community"
repo = "kickstart-nix.nvim"

[[sources]]
type = "github"
owner = "nix-community"
repo = "lanzaboote"

[[sources]]
type = "github"
owner = "nix-community"
repo = "linyaps-flake"

[[sources]]
type = "github"
owner = "nix-community"
repo = "luarocks-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "manix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "mavenix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "mineflake"

[[sources]]
type = "github"
owner = "nix-community"
repo = "naersk"

[[sources]]
type = "github"
owner = "nix-community"
repo = "namaka"

[[sources]]
type = "github"
owner = "nix-community"
repo = "napalm"

[[sources]]
type = "github"
owner = "nix-community"
repo = "neovim-nightly-overlay"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nh"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-bundle"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-direnv"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-doom-emacs"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-environments"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-eval-jobs"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-github-actions"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-index"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-index-database"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-init"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-installers"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-ld"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-melt"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-on-droid"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-on-droid-app"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-snapd"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-ts-mode"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-unit"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix-vscode-extensions"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix4nvchad"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nix4vscode"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixGL"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixago"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixago-extensions"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixd"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixdoc"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixhelm"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixos-anywhere"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixos-apple-silicon"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixos-facter"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixos-facter-modules"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixos-generators"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixos-vscode-server"

[[sources]]
type = "github"
owner = "nix-community"
repo = "NixOS-WSL"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixpkgs-lint"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixpkgs-swh"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixpkgs-terraform-providers-bin"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixpkgs-wayland"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixpkgs-xr"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixpkgs.lib"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nixt"

[[source]]
type = "github"
owner = "nix-community"
repo = "nixvim"

[[sources]]
type = "github"
owner = "nix-community"
repo = "noogle"

[[sources]]
type = "github"
owner = "nix-community"
repo = "NUR"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nur-packages-template"

[[sources]]
type = "github"
owner = "nix-community"
repo = "nurl"

[[sources]]
type = "github"
owner = "nix-community"
repo = "patsh"

[[sources]]
type = "github"
owner = "nix-community"
repo = "pip2nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "plasma-manager"

[[sources]]
type = "github"
owner = "nix-community"
repo = "poetry2nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "preservation"

[[sources]]
type = "github"
owner = "nix-community"
repo = "queued-build-hook"

[[sources]]
type = "github"
owner = "nix-community"
repo = "redoxpkgs"

[[sources]]
type = "github"
owner = "nix-community"
repo = "rnix-parser"

[[sources]]
type = "github"
owner = "nix-community"
repo = "robotnix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "rustowl-flake"

[[sources]]
type = "github"
owner = "nix-community"
repo = "srvos"

[[sources]]
type = "github"
owner = "nix-community"
repo = "steam-fetcher"

[[sources]]
type = "github"
owner = "nix-community"
repo = "stylix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "talon-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "templates"

[[sources]]
type = "github"
owner = "nix-community"
repo = "tree-sitter-nix"

[[sources]]
type = "github"
owner = "nix-community"
repo = "trustix"

[[sources]]
type = "github"
owner = "NixOS"
repo = "hydra"

[[sources]]
type = "github"
owner = "numtide"
repo = "flake-utils"

[[sources]]
type = "github"
owner = "PaddiM8"
repo = "kalker"

[[sources]]
type = "github"
owner = "PrismLauncher"
repo = "PrismLauncher"

[[sources]]
type = "github"
owner = "ryantm"
repo = "agenix"

[[sources]]
type = "github"
owner = "snowfallorg"
repo = "nixos-conf-editor"

[[sources]]
type = "github"
owner = "snowfallorg"
repo = "nix-software-center"

[[sources]]
type = "github"
owner = "stackbuilders"
repo = "nixpkgs-terraform"

[[sources]]
type = "github"
owner = "StardustXR"
repo = "telescope"

[[sources]]
type = "github"
owner = "surrealdb"
repo = "surrealdb"

[[sources]]
type = "github"
owner = "Svenum"
repo = "Solaar-Flake"

[[sources]]
type = "github"
owner = "TraceMachina"
repo = "nativelink"

[[sources]]
type = "github"
owner = "utensils"
repo = "mcp-nixos"

[[sources]]
type = "github"
owner = "Wazzaps"
repo = "fingerpaint"

[[sources]]
type = "github"
owner = "YaLTeR"
repo = "niri"

[[sources]]
type = "github"
owner = "yusdacra"
repo = "nix-cargo-integration"

[[sources]]
type = "github"
owner = "yusdacra"
repo = "rust-nix-templater"

[[sources]]
type = "github"
owner = "zed-industries"
repo = "zed"

[[sources]]
type = "gitlab"
owner = "pi-lar"
repo = "neuropil"

[[sources]]
type = "sourcehut"
owner = "~kerstin"
repo = "sway-timetracker"

[[sources]]
type = "sourcehut"
owner = "~munksgaard"
repo = "geomyidae-flake"
