name: "Test GH CLI without explicit token"

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  test-gh-without-token:
    runs-on: ubuntu-latest

    steps:
      - name: Test gh issue list
        shell: sh
        run: |
          echo "Testing gh issue list without explicit GITHUB_TOKEN..."
          gh issue list --state open -L 5 --json number,title
          echo "✓ gh issue list succeeded"

      - name: Test gh issue search
        shell: sh
        run: |
          echo "Testing gh issue search without explicit GITHUB_TOKEN..."
          TITLE="Test Issue"
          RESULT=$(gh issue list --state open --search "in:title $TITLE" -L 1 --json id --jq length)
          echo "Search result count: $RESULT"
          echo "✓ gh issue search succeeded"

      - name: Report success
        shell: sh
        run: |
          echo "✅ All gh CLI commands work without explicit GITHUB_TOKEN!"
          echo "The GITHUB_TOKEN is automatically available to gh CLI."
